import { AgentSkill } from "../../harness/index.ts";

export const ProposeNoteChangesSkill = AgentSkill.make({
  name: "propose-note-changes",
  description: "Propose adding, rewriting, or removing a block in a student's study notes for a material.",
  content: [
    "# Propose note changes",
    "",
    "Use this skill when the student asks you to add, rewrite, or remove something in the study notes",
    "of a material.",
    "",
    "You do NOT edit notes. You propose a change and the student reviews it in the \"Apuntes\" tab and",
    "accepts or rejects it. There is no command to accept, apply, or reject a proposal. If the student",
    "asks you to apply one, tell them they accept it themselves from their notes.",
    "",
    "Notes are generated per material, one block per topic of the index, each block headed by the topic",
    "name. Find the note with `artifacts list note`, then `artifacts show <artifactId>` for the outline",
    "and the block ids. Before a `replace`, read the current text with `artifacts block <artifactId>",
    "<blockId>` so you fold it in rather than overwrite it.",
    "",
    "## Command",
    "",
    "- `artifacts note propose <artifactId> '<json>'` — always wrap the JSON in single quotes.",
    "",
    "The JSON is `{\"rationale\":\"<one sentence: why you propose this>\",\"operation\":<operation>}`.",
    "",
    "Operations:",
    "- Insert a block:",
    "  `{\"type\":\"insert\",\"afterBlockId\":\"<block id, or null to put it first>\",\"markdown\":\"## Heading\\nProse...\",\"source\":{\"type\":\"material\",\"materialId\":\"<id>\",\"pages\":[4]}}`",
    "  `source` is optional: use `null` or omit it when the block does not come from a specific page.",
    "  Never copy page text into the block; the server fills the cached excerpt from the index.",
    "- Rewrite a block:",
    "  `{\"type\":\"replace\",\"blockId\":\"<id>\",\"markdown\":\"<the full new block text>\"}`",
    "- Remove a block:",
    "  `{\"type\":\"remove\",\"blockId\":\"<id>\"}`",
    "",
    "For a rewrite, `markdown` is the whole block rewritten, not a fragment to append: fold the current",
    "block text and what you and the student discussed into one coherent block. You do not send the old",
    "text: the server records it from the note itself. If the block changes before the student accepts,",
    "the accept is rejected and they see both versions side by side, so keep proposals fresh.",
    "",
    "## Merging or splitting blocks",
    "",
    "To merge block B into block A: one `replace` proposal on A with the combined text, and one separate",
    "`remove` proposal on B. To split a block: one `replace` on the original with the part that stays, and",
    "one `insert` for the new block. Each proposal is still one operation; the student accepts them one by",
    "one, so make the `replace` stand on its own even if the `remove` or `insert` is rejected.",
    "",
    "## Workflow",
    "",
    "1. `artifacts list note` to find the note, `artifacts show <artifactId>` for the block ids, and",
    "   `artifacts block <artifactId> <blockId>` for the current text of the block you will replace.",
    "2. Pick one operation: insert, replace, or remove. One idea per proposal.",
    "3. Build the JSON. It travels as a single shell argument in single quotes, so it must be valid JSON",
    "   on one line: escape every line break inside `markdown` as `\\n` and every double quote as `\\\"`.",
    "   Never put a raw line break or an unescaped quote inside a string.",
    "4. Run `artifacts note propose <artifactId> '<json>'`.",
    "5. Read the output. If it reports an error, the proposal was NOT saved: fix the JSON or the id and",
    "   try again. Only tell the student a proposal is waiting once the command confirms it saved.",
    "6. Point the student to the \"Apuntes\" tab of the material to accept or reject it.",
    "",
    "Keep proposals small and specific: one idea per proposal. Match the material's own vocabulary; do",
    "not translate a term the source uses."
  ].join("\n")
});
