import { AgentSkill } from "../../harness/index.ts";

// Sustituye a `create-study-artifacts`. El tutor ya NO crea Controles ni Exámenes (fase 3, decisión
// 4), ni entrega, ni corrige intentos (decisión 7): esa barrera vive en el código, no en este texto.
// Esta skill solo explica cómo se LEEN las pruebas, el perfil y los intentos, y a dónde mandar al
// alumno para generar una.
export const UseStudyAssessmentsSkill = AgentSkill.make({
  name: "use-study-assessments",
  description: "Read the student's study assessments (Controles and Exámenes), their attempts, and their study profile, to talk about how they are doing and what to review. You cannot create assessments or answer them.",
  content: [
    "# Use study assessments",
    "",
    "Use this skill when the student asks about their quizzes and tests, their attempts, their scores,",
    "or what they should review.",
    "",
    "## You do not create or answer assessments",
    "",
    "You CANNOT create a Control or an Examen, and you CANNOT submit or grade an attempt. The student",
    "generates them from the \"Pruebas\" tab of a material (a Control covers one topic of the index; an",
    "Examen covers the whole material), and only the student, from that tab, produces attempts that move",
    "their study profile. If the student asks you to \"make me a test\" or \"score my answers\", point them",
    "to the \"Pruebas\" tab. This is the same move the tutor already makes with study notes.",
    "",
    "(Same as with notes: to suggest a change to a note block, use the propose-note-changes skill. You",
    "propose; the student accepts.)",
    "",
    "## Read-only commands",
    "",
    "- `artifacts list [quiz|test]`: list the saved Controles and Exámenes.",
    "- `artifacts show <artifactId>`: one assessment as JSON (its questions, options, explanations, the",
    "  answer key, and each question's citation and, in a review, why it is there).",
    "- `artifacts attempts [artifactId]`: the attempts, newest first, with date, mode (practice / exam)",
    "  and score. Read-only.",
    "- `profile show <materialId>`: the study profile of a material, topic by topic.",
    "",
    "## The study profile has three separate signals",
    "",
    "`profile show` gives, per topic and SEPARATELY, never as one summary number:",
    "- how many questions the student got wrong on that topic,",
    "- how many hints they opened on that topic,",
    "- whether they marked that topic as important.",
    "",
    "They are kept apart on purpose. When you tell the student a topic is worth reviewing, say which",
    "signal brought it: \"you got this topic wrong twice\", or \"you opened a hint here\", or \"you marked",
    "this topic\". Never merge them into a single score, and never invent a number the profile does not",
    "give you.",
    "",
    "Blank answers and answers the judge could not evaluate are their own counts: a blank is not a wrong",
    "answer, and \"could not be evaluated\" is not a wrong answer either. Do not treat them as failures.",
    "",
    "## Names",
    "",
    "Use the interface's words: \"Control\" and \"Examen\", \"modo práctica\" and \"modo examen\". The contract",
    "still calls them `quiz` and `test`; the student sees Control and Examen.",
    "",
    "## Workflow",
    "",
    "1. If the question is about how the student is doing, run `profile show <materialId>` first.",
    "2. To talk about a specific assessment or its answer key, `artifacts list` then `artifacts show`.",
    "3. To talk about past attempts, `artifacts attempts <artifactId>`.",
    "4. When you recommend reviewing something, name the signal that brought it, and point the student to",
    "   the \"Pruebas\" tab, where they can generate a \"de repaso\" assessment focused on it."
  ].join("\n")
});
