import { AgentSkill } from "../../harness/index.ts";

export const UseStudyNotesSkill = AgentSkill.make({
  name: "use-study-notes",
  description: "Read a material's study note: its blocks, who wrote each one, where it comes from, and the material's mind map.",
  content: [
    "# Use study notes",
    "",
    "Use this skill when the student asks about their study notes, a block, sub-blocks, or \"the mind",
    "map\" of a material.",
    "",
    "Each material can have one study note: one block per topic of its index, so the note is the",
    "material's mind map. When the student says \"block\", \"blocks\", \"sub-blocks\", \"the note\" or \"the mind",
    "map\", they mean this note and its blocks, NOT the sections or headings of the PDF. If you are asked",
    "how many blocks there are, or about a specific block, read the note first: do not count PDF sections.",
    "",
    "## Commands",
    "",
    "- `artifacts list note`: every note, each ending in `material <id>`. Pick the one whose id matches",
    "  the material in question.",
    "- `artifacts show <artifactId>`: the note's outline. One line per block with its id, heading, author",
    "  (`tutor` or `student`), whether it is emphasised, its source (material pages, or a URL host), and",
    "  its size. It does NOT include the block text: it is the cheap overview.",
    "- `artifacts block <artifactId> <blockId>`: the full markdown of that block. Comma-separate ids",
    "  (`<idA>,<idB>`) to read several at once, for example to compare two blocks.",
    "",
    "So: `list note` to find it, `show` to see the structure and ids, `block` for the text of the blocks",
    "the question actually touches. Reading the whole note block by block is rarely needed.",
    "",
    "## What each block tells you",
    "",
    "A block's author is `tutor` (generated from the material) or `student` (written by the student, or",
    "a tutor proposal the student accepted). A block can carry a `source`: either material pages, or a",
    "URL the student added. An emphasised block is one the student marked as important. Use these fields",
    "when the student asks who wrote something, where it comes from, or what they marked.",
    "",
    "Once you have read the blocks you need you can answer about one, compare two, or point out where",
    "they overlap or leave a gap. You do not create, edit, merge or delete notes here: the student",
    "generates the note from the \"Apuntes\" tab, and any change to a block goes through the",
    "propose-note-changes skill (you propose, the student accepts).",
    "",
    "## Workflow",
    "",
    "1. `artifacts list note` to find the note for the material in question.",
    "2. `artifacts show <artifactId>` for the outline and the block ids.",
    "3. `artifacts block <artifactId> <blockId>` for the text of the blocks the question needs.",
    "4. If the note or its blocks do not contain enough evidence, say so clearly.",
    "5. When explaining, cite block headings, or page numbers when the block names its source."
  ].join("\n")
});
